function getChecklistId() {
  const gender = localStorage.getItem("gender");
  const climate = localStorage.getItem("climate");

  switch (gender + "-" + climate) {
    case "male-warm":
      return {
        id: "malewarm",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts",
          "Pants",
          "Shorts",
          "Hat/beanie",
          "Swimsuit/swim trunks",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Shaving kit",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Cologne/fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "male-mild":
      return {
        id: "malemild",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts",
          "Pants",
          "Shorts",
          "Hat/beanie",
          "Swimsuit/swim trunks",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Shaving kit",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Cologne/fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "male-cold":
      return {
        id: "malecold",
        section: "Clothing",
        items: [
          "Underwear",
          "Base layer",
          "Socks",
          "Shirts",
          "Pants",
          "Shorts",
          "Hat/beanie",
          "Swimsuit/swim trunks",
          "Shoes",
          "Boots/snowboots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Snowsuit/snowpants",
          "Gloves/mittens",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Shaving kit",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Cologne/fragrance",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "female-warm":
      return {
        id: "femalewarm",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/skirts",
          "Dress",
          "Hat/beanie",
          "Swimsuits/bikinis",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Gloves/mittens",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Perfume/fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "female-mild":
      return {
        id: "femalemild",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/skirts",
          "Dress",
          "Hat/beanie",
          "Swimsuits/bikinis",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Gloves/mittens",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Perfume/fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "female-cold":
      return {
        id: "femalecold",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/skirts",
          "Dress",
          "Hat/beanie",
          "Swimsuits/bikinis",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Gloves/mittens",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Perfume/fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "other-warm":
      return {
        id: "otherwarm",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/bottoms",
          "Hats",
          "Swimsuits",
          "Shoes",
          "Sandals",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "other-mild":
      return {
        id: "othermild",
        section: "Clothing",
        items: [
          "Underwear",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/bottoms",
          "Hat/beanie",
          "Swimsuits",
          "Shoes",
          "Sandals",
          "Boots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Fragrance",
          "Sunscreen",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    case "other-cold":
      return {
        id: "othercold",
        section: "Clothing",
        items: [
          "Underwear",
          "Base layer",
          "Socks",
          "Shirts/tops",
          "Pants",
          "Shorts/bottoms",
          "Hat/beanie",
          "Swimsuits",
          "Shoes",
          "Boots/snowboots",
          "Belt",
          "Pajamas",
          "Sweaters",
          "Jacket",
          "Snowsuit/snowpants",
          "Gloves/mittens",
          "Glasses",
          "Sun glasses",
        ],
        section: "Toiletries",
        items: [
          "Toothbrush",
          "Toothpaste",
          "Floss",
          "Mouthwash",
          "Razor/shaving supplies",
          "Shampoo",
          "Body wash",
          "Hair brush/comb",
          "Moisturizer/skin care",
          "Deodorant",
          "Fragrance",
          "Nail clippers/file",
          "Hairdryer",
          "Contacts/case/solution",
          "Makeup",
          "Hygiene products",
        ],
        section: "Personal Items",
        items: [
          "Medications",
          "Ear plugs",
          "Wallet/purse",
          "Daypack/backpack",
          "Travel pillow",
          "Pen/pencil",
          "Book",
          "Journal",
          "Reusable water bottle",
          "First aid supplies",
        ],
        section: "Electronics",
        items: [
          "Computer/tablet",
          "Mouse/keyboard",
          "Phone",
          "Camera/SD-cards",
          "Headphones/earbuds",
          "Chargers",
        ],
        section: "Travel Documents",
        items: [
          "Passport",
          "Identification card",
          "Driver's license",
          "Credit card",
          "Airline tickets",
          "Travel insurance",
          "Car rental documents",
          "Hotel/home rental documents",
          "Money/currency",
        ],
      };
    default:
      return "unknown";
  }
}


